apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: mint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        servis: app
    spec:
      containers:
      - name: app
        image: mifrepo.mimos.my:443/mi-intelligence/mint.app
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
        - name: MINT_DB_IP
          value: db.mint.svc.cluster.local
        - name: MINT_DB_USER
          value: root
        - name: MINT_DB_PASS
          value: bukhary
        - name: MINT_ENG_IP
          value: "10.1.71.156"
        - name: MINT_ENG_PORT
          value: "31770"
