apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admin 
  namespace: fssm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: admin
    spec:
      containers:
      - name: admin
        image: 10.1.70.189:5000/fssm/fssm-admin:test 
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8120
            protocol: TCP
        env:
        - name: MYSQL_DB_HOSTPORT
          value: 10.1.70.189:3306
        - name: MYSQL_DB_NAME
          value: fssm_master
        - name: MYSQL_DB_USER
          value: testuser
        - name: MYSQL_DB_PASS
          value: testuser
        - name: ARMC_URL
          value: http://10.1.71.33:8080/armc-core/armcService/
      imagePullSecrets:
      - name: fssm-repo


