apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web 
  namespace: fssm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: web
        image: 10.1.70.189:5000/fssm/fssm-web:test
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8090
            protocol: TCP
        env:
        - name: MYSQL_DB_HOSTPORT
          value: 10.1.70.189:3306
        - name: MYSQL_DB_NAME
          value: fssm_public
        - name: MYSQL_DB_USER
          value: testuser
        - name: MYSQL_DB_PASS
          value: testuser
        - name: ARMC_URL
          value: http://10.1.71.33:8080/armc-core/armcService/
        - name: ARMC_WS_URL
          value: http://ws:8091/armc/getAuthorization
        - name: SOLR_HOTSPORT
          value: http://solr:8983/solr
      imagePullSecrets:
      - name: fssm-repo
 
