apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: engine
  namespace: clip-mint
spec:
  replicas: 1
  template:
    metadata:
      labels:
        servis: engine
    spec:
      containers:
      - name: eng
        image: mifrepo.mimos.my:443/mi-clip_mi-int/mint.eng
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080 
            protocol: TCP
        env:
        - name: MINT_DB_IP
          value: mintdb.clip-mint.svc.cluster.local
        - name: MINT_DB_USER
          value: root
        - name: MINT_DB_PASS
          value: bukhary
        - name: MINT_KB_IP
          value: mintkb.clip-mint.svc.cluster.local
        - name: MINT_KB_USER
          value: bukhary
        - name: MINT_KB_PASS
          value: bukhary
        - name: MICLIP_DB_IP
          value: clipdb.clip-mint.svc.cluster.local
        - name: MICLIP_DB_NAME
          value: iclipcore
        - name: MICLIP_DB_USER
          value: root
        - name: MICLIP_DB_PASS
          value: password
        - name: MICLIP_APP_IP
          value: clipapp.clip-mint.svc.cluster.local
      imagePullSecrets:
        - name: mifrepo
