apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: $NAMESPACE
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  # You could also use NodePort to expose the service at a randomly-generated port
  # type: NodePort
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    servis: http-apache

